var errorCodes = {

    INVALID_POST_USER: 'POSTS_1001',
    INVALID_POST_MESSAGE: 'POSTS_1002',
    INVALID_POST_HASHTAG: 'POSTS_1003',
    POST_ORM_CREATE_ERROR: 'POSTS_1004',
    POST_HASTAG_ORM_CREATE_ERROR: 'POSTS_1005',
    POST_HASTAG_ORM_UPSERT_ERROR: 'POSTS_1006',
    POST_USERTAG_ORM_CHECK_ERROR: 'POSTS_1007',
    POST_USERTAG_HASHTAG_ORM_CREATE_ERROR: 'POSTS_1008',
    POST_HASHTAGS_OR_USERTAGS_NOT_FOUND: 'POSTS_1009',

    POST_TAGGED_POST_READ_ERROR: 'POSTS_1010',
    POST_FEED_READ_ERROR: 'POSTS_1011',
    POST_CREATED_USER_PUSH_ERROR: 'POSTS_1012',
    POST_HASH_TAG_NOT_FOUND: 'POSTS_1013',
    POST_HASH_TAGGED_POSTS: 'POSTS_1014',
    POST_READ_TO_UPDATE_POST_FAILED: 'POSTS_1015',
    POST_TO_UPDATE_NOT_FOUND: 'POSTS_1016',
    POST_UPDATE_USER_PUSH_ERROR: 'POSTS_1017',
    POST_USERTAG_HASHTAG_ORM_UPDATE_ERROR: 'POSTS_1018',

    USER_INVALID: 'USERS_1050',
    USER_NOT_FOUND_TO_FOLLOW: 'USERS_1051'

}

module.exports = errorCodes;
