var errorCodes = {

    INVALID_POST_USER: 'POSTS_1001',
    INVALID_POST_MESSAGE: 'POSTS_1002',
    INVALID_POST_HASHTAG: 'POSTS_1003',
    POST_ORM_CREATE_ERROR: 'POSTS_1004',
    POST_HASTAG_ORM_CREATE_ERROR: 'POSTS_1005',
    POST_HASTAG_ORM_UPSERT_ERROR: 'POSTS_1006',
    POST_USERTAG_ORM_CHECK_ERROR: 'POSTS_1007',
    POST_USERTAG_HASHTAG_ORM_CREATE_ERROR: 'POSTS_1008',
    POST_HASHTAGS_OR_USERTAGS_NOT_FOUND: 'POSTS_1009',

    POST_TAGGED_POST_READ_ERROR: 'POSTS_1010',
    POST_FEED_READ_ERROR: 'POSTS_1011'

}

module.exports = errorCodes;
